\prompt	'Type in the name of the database \n-> ' DB_NAME
\prompt 'Type in the username for the role \n-> ' USER_NAME
\prompt 'Type in the password for the role \n-> ' PASSWORD


CREATE ROLE :USER_NAME WITH PASSWORD :PASSWORD;
ALTER ROLE :USER_NAME WITH LOGIN
CREATE DATABASE :USER_NAME;
GRANT CONNECT ON DATABASE :DB_NAME TO :USER_NAME;
# MIGHT BE NEEDED TO CONNECT ON DB AS SUDO
GRANT USAGE ON SCHEMA public TO :USER_NAME;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO :USER_NAME;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public :USER_NAME;
GRANT SELECT ON ALL VIEWS IN SCHEMA public :USER_NAME;